services:
  - type: web
    name: Wink-V2-Backend
    env: python
    buildCommand: "poetry install"
    startCommand: "gunicorn app:app" 
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-database
          property: connectionString
